#!/usr/bin/env bash

# Meant to be called as a usual command, with the script in the PATH:
# $ imovo-shell <product_name>

if test $# -ne 1
then
	echo "$0: wrong number of arguments." 1>&2
	exit 1
fi

get_script_directory() {
	script_dir=`dirname "$BASH_SOURCE"`
	absolute_script_dir=`cd "$script_dir" && pwd`
	echo "$absolute_script_dir"
}

script_directory="`get_script_directory`"

pushd "${script_directory}/../utils/"
source ./imovo-utils-setup-env.sh "$1"
popd

# Nested shell.
bash
